name = "LeanQIR"
version = "0.1.0"
defaultTargets = ["LeanQIR"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanQIR"
globs = ["LeanQIR", "LeanQIR.Syntax", "LeanQIR.State", "LeanQIR.Semantics", "LeanQIR.QIR.+"]

[[lean_lib]]
name = "LeanQIR.Examples"
globs = ["LeanQIR.Examples.*"]

[[lean_exe]]
name = "emit_bell"
root = "LeanQIR.Examples.Bell"
